### PR TITLE
Highlight vclConditional as Conditional

### PR DESCRIPTION
**Pull request by utix**
Add vclConditional as Conditional

### CODE REVIEW

**Comment by fgsch** [comment]
Thanks for the PR. 

Haven't had time to look at this yet but hopefully I will review it next week.

**Comment by utix** [comment]
@fgsch have you found few minutes to review my PR ? Don't hesitate if you want me to rewrite it

**Comment by fgsch** [comment]
Sorry, I'm still a bit swamped atm. I will try to take a look over the weekend.

**Comment by fgsch** [comment]
Thanks for your patience and the PR. I've merged it.

**Pull request merged**
